package com.example.signup

const val NAV_TERM = "term"
const val NAV_PHONE = "phone"
const val NAV_NAME = "name"
const val NAV_NICK = "nick"
const val NAV_INFO = "info"
const val ERROR_ALREADY_SIGN_UP = "Already SignUp"
const val ERROR_TIME_OUT = "Time out"
const val ERROR_FAIL_SMS = "Fail to request SMS"
const val MALE = "male"
const val FEMALE = "female"
const val ISYear = "isYear"
const val ISDay = "isDay"
const val ISMonth = "Month"
const val ISCity = "city"
const val ISArea = "area"
